-- products_seed.sql
-- Inserciones masivas para la tabla `products`.
-- NOTA: Antes de ejecutar, asegúrate de usar la base de datos correcta:
--    CREATE DATABASE farmacia; USE farmacia;
-- Luego importa este archivo: SOURCE sql/products_seed.sql; o usa el cliente MySQL.

INSERT INTO products (name, price, category, description, icon) VALUES
('Aceite de hígado de bacalao emulsión', 40.00, 'vitaminas', 'Frasco 180 ml', ''),
('Acetaminofén', 0.30, 'analgesicos', 'Tableta 500 mg', ''),
('Acetaminofén (supositorio)', 5.00, 'analgesicos', 'Supositorio 100 mg', ''),
('Acetaminofén + cafeína', 2.50, 'analgesicos', '500 mg + 65 mg Tableta', ''),
('Acetaminofén gotas pediátricas', 15.00, 'analgesicos', 'Frasco Gotero 15 ml', ''),
('Acetaminofén jarabe', 15.00, 'analgesicos', 'Frasco 120 ml', ''),
('Acetato de medroxiprogesterona', 50.00, 'hormonas_contraceptivas', 'Inyección de Liberación Retardada 150 mg/ml Vial', ''),
('Acetazolamida', 8.00, 'diureticos', 'Tableta 250 mg', ''),
('Acetilcisteína ampolla', 15.00, 'mucoliticos', 'Ampolla 300 mg / 3 ml', ''),
('Acetilcisteína polvo', 10.00, 'mucoliticos', 'Sobre Polvo granulado 200 mg', ''),
('Aciclovir', 1.50, 'antivirales', 'Tableta 400 mg', ''),
('Aciclovir crema', 10.00, 'antivirales', 'Tubo 5 g', ''),
('Aciclovir suspensión', 40.00, 'antivirales', 'Frasco 60 ml', ''),
('Ácido acetilsalicílico', 1.00, 'analgesicos', 'Tableta 325 mg', ''),
('Ácido acetilsalicílico (uso cardiaco)', 0.50, 'cardio', 'Tableta 81 mg', ''),
('Ácido ascórbico (vit. c)', 2.00, 'vitaminas', 'Tableta 500 mg', ''),
('Ácido fólico', 0.20, 'vitaminas', 'Tableta 5 mg', ''),
('Ácido fólico jarabe', 13.00, 'vitaminas', 'Frasco 120 ml', ''),
('Ácido fólico + vit. b12 jarabe', 25.00, 'vitaminas', 'Frasco 120 ml', ''),
('Ácido mefenámico', 0.70, 'antiinflamatorios', 'Tableta 500 mg', ''),
('Ácido valproico (valproato sódico)', 12.00, 'antiepilépticos', 'Tableta 500 mg', ''),
('Ácido valproico solución', 90.00, 'antiepilépticos', 'Frasco 40 mL', ''),
('Adrenalina', 7.00, 'cardio', 'Ampolla 1 mg / 1 ml', ''),
('Agua para inyectable 5ml', 3.00, 'solubilizantes', 'Ampolla 5 ml', ''),
('Agua para inyectable 10ml', 3.00, 'solubilizantes', 'Ampolla 10 ml', ''),
('Albendazol (dosis única)', 1.00, 'antiparasitarios', 'Tableta 400 mg', ''),
('Albendazol masticable', 10.00, 'antiparasitarios', 'Tableta 400 mg', ''),
('Albendazol suspensión', 5.00, 'antiparasitarios', 'Sobre 400 mg / 10 ml', ''),
('Albúmina humana 20%', 2000.00, 'sustituto_plasma', 'Frasco Ampolla 50 ml', ''),
('Alcohol isopropílico 70º', 20.00, 'antisepticos', 'Frasco 120 ml', ''),
('Alendronato', 1.00, 'osteo', 'Tableta 70 mg', ''),
('Algodón planchado 4x4', 15.00, 'insumos_hospitalarios', 'Venda 4” x 4”', ''),
('Algodón planchado 6x4', 15.00, 'insumos_hospitalarios', 'Venda 6" x 4', ''),
('Algodón torunda', 5.00, 'insumos_hospitalarios', 'Funda 7 g', ''),
('Alopurinol', 1.50, 'antigotosos', 'Tableta 300 mg', ''),
('Ambroxol', 3.00, 'mucoliticos', 'Tableta 30 mg', ''),
('Ambroxol jarabe', 15.00, 'mucoliticos', 'Frasco 120 ml', ''),
('Amikacina', 15.00, 'antibacterianos', 'Vial 500 mg / 2 ml', ''),
('Aminosidina', 18.00, 'antiamebicos', 'Tableta 250 mg', ''),
('Amiodarona', 4.00, 'cardio', 'Tableta 200 mg', ''),
('Amitriptilina', 1.50, 'antidepresivos', 'Tableta 25 mg', ''),
('Amlodipina 5mg', 0.20, 'cardio', 'Tableta 5 mg', ''),
('Amlodipina 10mg', 0.20, 'cardio', 'Tableta 10 mg', ''),
('Amoxicilina cápsula 500mg', 1.00, 'antibacterianos', 'Cápsula 500 mg', ''),
('Amoxicilina + ácido clavulánico cápsula', 5.00, 'antibacterianos', 'Cápsula 500 mg / 125 mg', ''),
('Amoxicilina + ácido clavulánico suspensión', 60.00, 'antibacterianos', 'Frasco 60 ml', ''),
('Amoxicilina suspensión 120ml', 25.00, 'antibacterianos', 'Frasco 120 ml', ''),
('Ampicilina cápsula 500mg', 1.50, 'antibacterianos', 'Cápsula 500 mg', ''),
('Ampicilina vial 1g', 10.00, 'antibacterianos', 'Vial 1 g', ''),
('Anestésico local + astringente + antiinflamatorio', 15.00, 'antihemorroidales', 'Supositorio', ''),
('Antiespasmódico (n-butil bromuro-hioscina) tableta', 5.00, 'antiespasmodicos', 'Tableta 10 mg', ''),
('Antiespasmódico (n-butil bromuro-hioscina) ampolla', 15.00, 'antiespasmodicos', 'Ampolla 20 mg / 1 ml', ''),
('Antigripal jarabe', 15.00, 'antigripal', 'Frasco 120 ml', ''),
('Antigripal tableta (blíster 10)', 3.00, 'antigripal', 'Blíster de 10 Tabletas', ''),
('Atenolol 50mg', 0.20, 'cardio', 'Tableta 50 mg', ''),
('Atenolol 100mg', 0.30, 'cardio', 'Tableta 100 mg', ''),
('Atenolol + clortalidona 50/12.5', 1.50, 'cardio', 'Tableta 50 mg / 12.5 mg', ''),
('Atenolol + clortalidona 100/25', 2.00, 'cardio', 'Tableta 100 mg / 25 mg', ''),
('Atropina', 5.00, 'antiarritmicos', 'Ampolla 1 mg / 1 ml', ''),
('Azitromicina cápsula 500mg', 4.00, 'antibacterianos', 'Cápsula 500 mg', ''),
('Azitromicina suspensión 30ml', 25.00, 'antibacterianos', 'Frasco 30 ml', ''),
('Bajante de suero', 10.00, 'insumos_hospitalarios', 'Unidad', ''),
('Bastón ajustable de aluminio (cuatro apoyos)', 350.00, 'ortopedicos', 'Unidad', ''),
('Bastón ajustable de aluminio (un apoyo)', 200.00, 'ortopedicos', 'Unidad', ''),
('Betahistina', 3.00, 'antivertiginosos', 'Tableta 6 mg', ''),
('Betametasona 0.1% crema', 50.00, 'dermatologicos', 'Tubo 15 g', ''),
('Bismuto subsalicilato suspensión', 50.00, 'antidiarreicos', 'Frasco 100 mL', ''),
('Bisoprolol 2.5mg', 3.00, 'cardio', 'Tableta 2.5 mg', ''),
('Bisoprolol 5mg', 3.00, 'cardio', 'Tableta 5 mg', ''),
('Bolsa colectora de orina (adulto)', 10.00, 'insumos_hospitalarios', 'Unidad', ''),
('Bolsa colectora de orina (pediátrica)', 5.00, 'insumos_hospitalarios', 'Unidad', ''),
('Bromhexina jarabe 60ml', 10.00, 'mucoliticos', 'Frasco 60 ml', ''),
('Budesonida 100 mcg', 350.00, 'antiasmaticos', 'Spray Frasco Nasal', ''),
('Bupivacaína pesada 0.5%', 15.00, 'anestesico_local', 'Vial 4 ml', ''),
('Cabestrillo grande', 150.00, 'ortopedicos', 'Unidad', ''),
('Cabestrillo mediano', 150.00, 'ortopedicos', 'Unidad', ''),
('Cabestrillo pequeño', 150.00, 'ortopedicos', 'Unidad', ''),
('Calamina 0.15%', 40.00, 'dermatologicos', 'Fco. 120ml Frasco', ''),
('Calcio carbonato + vit. d3', 1.00, 'vitaminas', 'Tableta 600 mg / 400 UI', ''),
('Candesartán 16 mg', 2.50, 'cardio', 'Tableta 16 mg', '');